dist:
  xenial

sudo:
  required

addons:
  postgresql: "9.4"

services:
  - mysql

language:
  python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"
    - POSTGRES_URL=postgresql://postgres@localhost:5432/postgres
    - SQLITE_URL=sqlite:///:memory:
    - MYSQL_URL=mysql+pymysql://root@localhost:3306/test?charset=utf8

before_install:
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - sudo apt-get install sqlite3-pcre
  - echo ".load /usr/lib/sqlite3/pcre.so" > ~/.sqliterc.

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls


jobs:
  include:
    - stage: release
      if: tag IS present
      python: 3.8
      deploy:
        provider: pypi
        user: roll
        distributions: sdist bdist_wheel
        skip_cleanup: true
        on:
          tags: true
        password:
          secure: T2DlIzbiLOrOv0Ox2wPaaoEA701dZufaE/MaSn80gL56zbV/NEMNRYK2aH2mpjFDPDHVkXnAT2LemXG8njhVw6XwFxEqwvFb04DtudpBCdzrPfGeq/Q3erl34mMkeV6+KaSTlAxZqCVhUOfSbwyFU1Abe1ASrFwjYrFhGEk/VpG94SYUthzZU+YT92dfYGTISEiQdeOi4B69hnKJ5Tchl4LL+OnPss2AS//ArZMmqWvG6ftP3Cavwt49fU4lGyfQSNEmsZXwKadBa9HMHPmXcucGH9b8ezM7KoPR82yWys4VFuFsKzsZJn2wW9hRDvKIJqCnd84Op9ys9pF8yzqEL/w1w2xpJswMrs8CNR2WJVcjP4OKrr/d/cQ0dJnNO0MbIXVL3FKS1m8cOAvELoOT6swr/xdMfV+oAPL66nYP9/oYaHt3qmI7kgqUnWyVVfi6ZcjdM893cg9LHTTPrQhvwu9vsIuFFVtPrdNUxo01zeQ1fssnxZ7WWHScM4Dcq6HmhcPug/ZQ109lfdvZddAwPxoL6WOyoH3Fbo4EXdxrVD8lxu7BRFsNMcuNjsNCimPvaoHKZK+WFZv71Vl1tep05WCvc35rkCJcP9SxiJnlJZLUYB8Feed9q8/DWEruDjKCW1/79xZCpudrfKb+S+wnViIf04pvj/S7pRYqxtEg6OU=
