sudo:
  required

dist:
  trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
      - pandoc

services:
  - mysql

language:
  python

python:
  - 2.7
  - 3.3
  # - 3.4
  - 3.5
  - 3.6

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"
    - MYSQL_URL=mysql://root@localhost:3306/test
    - POSTGRES_URL=postgresql://postgres@localhost:5432/postgres
    - SQLITE_URL=sqlite:///:memory:

before_install:
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: T2DlIzbiLOrOv0Ox2wPaaoEA701dZufaE/MaSn80gL56zbV/NEMNRYK2aH2mpjFDPDHVkXnAT2LemXG8njhVw6XwFxEqwvFb04DtudpBCdzrPfGeq/Q3erl34mMkeV6+KaSTlAxZqCVhUOfSbwyFU1Abe1ASrFwjYrFhGEk/VpG94SYUthzZU+YT92dfYGTISEiQdeOi4B69hnKJ5Tchl4LL+OnPss2AS//ArZMmqWvG6ftP3Cavwt49fU4lGyfQSNEmsZXwKadBa9HMHPmXcucGH9b8ezM7KoPR82yWys4VFuFsKzsZJn2wW9hRDvKIJqCnd84Op9ys9pF8yzqEL/w1w2xpJswMrs8CNR2WJVcjP4OKrr/d/cQ0dJnNO0MbIXVL3FKS1m8cOAvELoOT6swr/xdMfV+oAPL66nYP9/oYaHt3qmI7kgqUnWyVVfi6ZcjdM893cg9LHTTPrQhvwu9vsIuFFVtPrdNUxo01zeQ1fssnxZ7WWHScM4Dcq6HmhcPug/ZQ109lfdvZddAwPxoL6WOyoH3Fbo4EXdxrVD8lxu7BRFsNMcuNjsNCimPvaoHKZK+WFZv71Vl1tep05WCvc35rkCJcP9SxiJnlJZLUYB8Feed9q8/DWEruDjKCW1/79xZCpudrfKb+S+wnViIf04pvj/S7pRYqxtEg6OU=
